name: 'Aller Sweden Labrador GitHub Action'
description: 'Disables manual merge for PRs in Labrador repo'
inputs:
  GITHUB_TOKEN: 
    description: 'GitHub Token'
    required: true
  WORKFLOW_ACTION:
    description: 'What the action should do'
    required: true
  TRIGGER_BRANCH:
    description: 'Which branch will trigger CodePipeline'
    required: false
  BASE_BRANCH:
    description: 'The name of the base branch'
    required: false
runs:
  using: 'node16'
  main: 'index.js' 